[package]
name = "rust_hawktracer"
version = "0.0.2"
authors = ["Alexandru <alex.ene0x11@gmail.com>"]
build = "build.rs"
links = "hawktracer"

[build-dependencies]
cmake = "0.1"

[build-dependencies.bindgen]
version = "0.37.0"
optional = true

[features]
profiling_enabled = []
generate_bindings=["bindgen"]
